spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      repositories:
        enabled: false

logging:
  level:
    root: WARN
    com.kole.platform: INFO