spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://127.0.0.1:5433/kole_db}
    username: ${DATABASE_USERNAME:kole_user}
    password: ${DATABASE_PASSWORD:change_me_locally}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    com.kole.platform: DEBUG
    org.hibernate.SQL: DEBUG
